# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Shuai666/IP_test/glitchfilter_4_4_2gate_dmatimeout/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_ad7606_sample_0_0/system_ad7606_sample_0_0.xci
# IP: The module: 'system_ad7606_sample_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Shuai666/IP_test/glitchfilter_4_4_2gate_dmatimeout/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_ad7606_sample_0_0/src/afifo_1/afifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] -quiet

# XDC: e:/Shuai666/IP_test/glitchfilter_4_4_2gate_dmatimeout/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_ad7606_sample_0_0/src/afifo_1/afifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/Shuai666/IP_test/glitchfilter_4_4_2gate_dmatimeout/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_ad7606_sample_0_0/src/afifo_1/afifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: E:/Shuai666/IP_test/glitchfilter_4_4_2gate_dmatimeout/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_ad7606_sample_0_0/system_ad7606_sample_0_0.xci
# IP: The module: 'system_ad7606_sample_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Shuai666/IP_test/glitchfilter_4_4_2gate_dmatimeout/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_ad7606_sample_0_0/src/afifo_1/afifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] -quiet

# XDC: e:/Shuai666/IP_test/glitchfilter_4_4_2gate_dmatimeout/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_ad7606_sample_0_0/src/afifo_1/afifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/Shuai666/IP_test/glitchfilter_4_4_2gate_dmatimeout/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_ad7606_sample_0_0/src/afifo_1/afifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
